name: _step.build

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up Python version
        uses: actions/setup-python@main
        with:
          python-version: "3.12"

      - name: Create and start virtual enviroment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Main
        run: python main.py

      - name: Zipping builds
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip .builds

      - name: Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build
          path: ./build.zip
